spring:
  application:
    name: consumer
  cloud:
    config:
      discovery:
        serviceId: register-server
        enabled: true
server:
  port: 8804
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://112.74.161.190:8000/eureka/
feign:
  hystrix:
    enabled: true