spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: WKQ!123!wkq
    url: jdbc:mysql://aliyun:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: admin
    password: admin
    host: aliyun
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: aliyun
    database: 0
    port: 6379
    password: 123456
  cache:
    cache-names: menus_cache
server:
  port: 8088
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/